spring.datasource.name=CraveHub
spring.datasource.url=jdbc:mysql://localhost:3306/CraveHub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Bhagat@04
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.oauth2.client.registration.google.client-id=23875451094-fqb5p7lo8g05jkt7lhduvde5dods7hc8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

razorpay.key.id=rzp_test_SmO9iDl0lLi7yb
razorpay.key.secret=zkzelNVQ71Cc8SchV78Yjloh

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=7204anshu@gmail.com
spring.mail.password=scni qrmk gvrv vmkp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
